//! Profile environment setup — generates shell snippets for PATH resolution.
//!
//! The two-layer profile model:
//! 1. User profile: ~/.config/bingux/profiles/current/bin/ (overrides)
//! 2. System profile: /system/profiles/current/bin/ (fallback)
//!
//! User PATH: user-profile/bin : system-profile/bin : /bin : /sbin

/// Generate an /etc/profile.d snippet for Bingux PATH setup.
pub fn generate_profile_snippet(system_profile: &str, session_root: &str) -> String {
    format!(
        r#"# Bingux profile setup — generated by bsys-config
# Two-layer PATH: user profile → system profile → base system

# System profile (generation-managed)
export BINGUX_SYSTEM_PROFILE="{system_profile}"

# Session root (volatile packages, cleared on reboot)
export BINGUX_SESSION_ROOT="{session_root}"

# User profile (per-user overrides)
if [ -n "${{HOME}}" ]; then
    export BINGUX_USER_PROFILE="${{HOME}}/.config/bingux/profiles/current"
fi

# Build PATH: session → user → system → base
_bingux_path=""
[ -d "$BINGUX_SESSION_ROOT/bin" ] && _bingux_path="$BINGUX_SESSION_ROOT/bin"
[ -d "$BINGUX_USER_PROFILE/bin" ] && _bingux_path="${{_bingux_path:+$_bingux_path:}}$BINGUX_USER_PROFILE/bin"
_bingux_path="${{_bingux_path:+$_bingux_path:}}$BINGUX_SYSTEM_PROFILE/bin"
export PATH="${{_bingux_path}}:/bin:/sbin:/usr/bin:/usr/sbin"

# Library path
export LD_LIBRARY_PATH="/lib64:/usr/lib64"

# Package store
export BPKG_STORE_ROOT="/system/packages"

# Bingux version
export BINGUX_VERSION="0.1.0"

unset _bingux_path
"#
    )
}

/// Generate a login shell prompt.
pub fn generate_prompt_snippet() -> String {
    r#"# Bingux shell prompt
if [ "$(id -u)" -eq 0 ]; then
    PS1='\[\e[1;31m\]bingux\[\e[0m\]:\[\e[1;34m\]\w\[\e[0m\]# '
else
    PS1='\[\e[1;36m\]bingux\[\e[0m\]:\[\e[1;34m\]\w\[\e[0m\]$ '
fi
"#
    .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn profile_snippet_has_system_path() {
        let snippet = generate_profile_snippet(
            "/system/profiles/current",
            "/run/bingux/session",
        );
        assert!(snippet.contains("/system/profiles/current"));
        assert!(snippet.contains("/run/bingux/session"));
        assert!(snippet.contains("BPKG_STORE_ROOT"));
        assert!(snippet.contains("PATH="));
    }

    #[test]
    fn prompt_snippet_has_colors() {
        let snippet = generate_prompt_snippet();
        assert!(snippet.contains("PS1="));
        assert!(snippet.contains("bingux"));
    }

    #[test]
    fn two_layer_path_order() {
        let snippet = generate_profile_snippet("/system/profiles/current", "/run/bingux/session");
        // Session should come before system in the PATH construction
        let session_pos = snippet.find("BINGUX_SESSION_ROOT/bin").unwrap();
        let system_pos = snippet.find("BINGUX_SYSTEM_PROFILE/bin").unwrap();
        assert!(session_pos < system_pos, "session should be before system in PATH");
    }
}
